[package]
name = "ray-ten"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version ="0.3" }
lazy_static = "1.4.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1.5"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true